// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uznjfbqnivhfrotrtzzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6bmpmYnFuaXZoZnJvdHJ0enpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDI4OTIsImV4cCI6MjA2NTk3ODg5Mn0.9o2iKujeSRexB434l_F7kO2eAvWhagx_xcm2ruQkc7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);